### ISSUE TITLE
Suggestion: Change Title Color

### ISSUE THREAD

**Issue by nicksgithubuser2** [nicksgithubuser1/github-crash-course-1#1]
I think it looks better if the main title is a bit more orange

The styling rule could be changed like list

```css

h1 {
  color: #efa82e;
}

```
